version: 0.2

phases:
  pre_build:
    commands:
      - echo "Starting frontend deployment..."
      - echo "Deploying from current front-end folder"
  build:
    commands:
      - echo "No build needed for static HTML/CSS/JS"
  post_build:
    commands:
      - echo "Syncing frontend files to B1 frontend bucket..."
      - aws s3 sync . s3://smart-photo-frontend-gurjeet --delete --exclude ".git/*" --exclude "README.md" --exclude "buildspec.yml"
      - echo "Frontend deployed successfully"

artifacts:
  files:
    - index.html
    - app.js
    - style.css
    - sdk-search/**/*